### ISSUE TITLE
Accessing the transform parameters and applying them

### ISSUE THREAD

**Issue by nvladimus** [SuperElastix/elastix-napari#21]
Hi, everyone,
Many thanks for creating this plugin, it works right out of the box on my data! 
I am registering light-sheet imaged mouse brains to Allen Brain Atlas. After a 2-step registration (affine, then Bspline) I would like to take those transform parameters and apply them to the Allen Brain Atlas **labels** file. Is there a way to do this? Can I fetch the registration parameter files somehow from the plugin? Can I then apply them to a new stack which contains labels?
Many thanks! 🙏 
Nikita

**Comment by MathieuBo** [comment]
I would be very interested in being able to do that as well!

**Comment by ntatsisk** [comment]
Hi @nvladimus and @MathieuBo, as far as I understand this is not possible at the moment. However, it sounds quite reasonable so I will take a look and try to implement it.

**Comment by ntatsisk** [comment]
I added the option to save the transform parameters with #30. I plan to add a widget for the transformix so that you can also transform the labels inside napari.

**Comment by nvladimus** [comment]
Many thanks!

**Comment by ntatsisk** [comment]
Hi @nvladimus and @MathieuBo,
FYI
* I just added the transformix widget with https://github.com/SuperElastix/elastix_napari/pull/31 - to be released with the new version
* You can write the result images to disk by the PR https://github.com/InsightSoftwareConsortium/napari-itk-io/pull/9 in `napari-itk-io` plugin that  gets installed together with the current plugin
* We are giving a demo about the elastix-napari plugin this week (https://github.com/SuperElastix/elastix/discussions/868). If you happen to drop by we could discuss your use cases - that would be interesting!

Let me know if you try the changes, and also about any other feature request :)

**Comment by ntatsisk** [comment]
Great! I am closing this, feel free to open a new issue if anything does not work as expected.

For a list of possible future features, you can take a look here: https://github.com/SuperElastix/elastix-napari/issues/35
